---
- name: Repos - Enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest

- name: Repos - Install mariadb repo
  copy: src=mariadb.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

