---
- name: Users - Configure members of wheel group for passwordless sudo
  sudo: yes
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present
  tags:
    - users
